# Site/SEO settings
email: me@insanj.com
baseurl: ""
permalink: /:year/:title/
google_analytics: 

name: insane.jpg
title: insane.jpg
description: 🎬 i make siege youtube videos
url: https://insane.pink
twitter_username: insanj
default_img: /assets/images/avatar.jpg
social:
  - name: twitter
    url: https://twitter.com/insanj
  - name: github
    url: https://github.com/insanj
  - name: youtube 
    url: https://gaming.youtube.com/insanj

# Contact settings
contact_img: /assets/images/avatar.jpg

# Author settings
author:
  - name: insane.jpg
    bio: 🎬 i make siege youtube videos
    url: https://insanj.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-app-engine
  
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude: [vendor]

app_engine:
  runtime: go
  api_version: go1
  default_expiration: 300s

